### ISSUE TITLE
Problems while executing RefactoringMiner

### ISSUE THREAD

**Issue by lucasrafael1901** [tsantalis/RefactoringMiner#277]
Hi, I got the following error while running the RefacoringMiner class:

Execution failed for task ':RefactoringMiner.main()'.
> Process 'command 'C:/Program Files/Java/jdk-11.0.16/bin/java.exe'' finished with non-zero exit value 1

I already tried diferent versions of java, and java_home configs but the same error persists.

Version of RefactoringMiner: 2.3.2

**Comment by rdurelli** [comment]
I'm facing a similar problem: using the MAVEN dependency below I get the following error: Cannot invoke "org.kohsuke.github.GitHub.getRepository(String)" because "gitHub" is null

` <dependency>
            <groupId>com.github.tsantalis</groupId>
            <artifactId>refactoring-miner</artifactId>
            <version>2.3.2</version>
        </dependency>`

**Comment by mkshiblu** [comment]
It seems the chrome extension is also not working.

![image](https://user-images.githubusercontent.com/15908043/186708158-d837b6bf-dcae-447a-8a0e-39ec06d42cfd.png)

![image](https://user-images.githubusercontent.com/15908043/186708212-d5c166f9-27b7-48b6-9e38-3f8c4e64a30a.png)

**Comment by tsantalis** [comment]
@lucasrafael1901 
Thank you for reporting this issue. Please give me more information about what you tried to do.
How did you execute main(). What arguments did you pass?

@rdurelli 
Refael, please make sure you have configured your personal GitHub OAuth key in `github-oauth.properties`
It seems you are trying to use the GitHub API.

@mkshiblu 
I did a fresh boot of the RefactoringMiner service, building the project from the most recent commit. The chrome extension should be working now.

**Comment by lucasrafael1901** [comment]
I build the project with intelliJ and got the error when i run the RefactoringMiner class with no others arguments, just using the run button.

**Comment by tsantalis** [comment]
@lucasrafael1901
Go to **Edit Configurations**
and add the program arguments to the **CLI arguments** section, as shown in the screenshot

![Screenshot from 2022-08-26 19-59-51](https://user-images.githubusercontent.com/1483516/187005593-624192f8-09f6-4dc4-ab09-89fa99dc0d65.png)

For example the arguments I added are:
> -c
> tmp1/refactoring-toy-example
> 36287f7c3b09eff78395267a3ac0d7da067863fd
> -json
> output.json

The tool executed fine, as shown in the screenshot, and the output was saved in file `output.json` as specified in the arguments.

![Screenshot from 2022-08-26 20-05-35](https://user-images.githubusercontent.com/1483516/187005726-652e1289-f564-4982-8263-d551d1a3b0ef.png)

**Comment by lucasrafael1901** [comment]
@tsantalis thank you for the support, but i still can't run the project. Here's a .txt file with the full stackTrace error
[text.txt](https://github.com/tsantalis/RefactoringMiner/files/9440127/text.txt)

That's how java_home is configured
![image](https://user-images.githubusercontent.com/88104745/187086384-15b01318-b890-4f34-88ec-0b79ed66ab54.png)
![image](https://user-images.githubusercontent.com/88104745/187086403-04cd2cfe-90df-4779-a683-1625454ab1ee.png)

And that's the following configurations of IDE Run
![image](https://user-images.githubusercontent.com/88104745/187086499-0d0b6a71-4190-4180-8ae6-5763f0affbec.png)

And sorry for the previous delay.

**Comment by tsantalis** [comment]
@lucasrafael1901 
The arguments I gave you, assume the repository https://github.com/danilofes/refactoring-toy-example.git is already cloned in folder `tmp1`
Why is `org.refactoringminer.RefactoringMiner` in a red border? What is the error message by IntelliJ ?

Can you try please to build the project from command line using the commands
`gradlew distZip`
or
`gradlew jar`

**Comment by lucasrafael1901** [comment]
@tsantalis Hello,
Both build successfully, but got the same error "Process 'command 'C:/Program Files/Java/jdk-11.0.16/bin/java.exe'' finished with non-zero exit value 1"
![image](https://user-images.githubusercontent.com/88104745/187229789-06b2a5d4-63e6-4de9-b61b-bab33f76d4e1.png)

I cloned the toy-example, but got a new error, when i try to "RUN WITH COVERAGE" at IntelliJ
![image](https://user-images.githubusercontent.com/88104745/187229995-5bbb2bd8-9466-49e7-bb8d-ea1d0d77bec5.png)

```"C:\Program Files\Java\jdk-11.0.16\bin\java.exe" -javaagent:C:\Users\lucas\AppData\Local\JetBrains\IdeaIC2022.2\testAgent\intellij-coverage-agent-1.0.673.jar=C:\Users\lucas\AppData\Local\Temp\coverage1args -Didea.new.sampling.coverage=true -Dcoverage.ignore.private.constructor.util.class=true "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2\lib\idea_rt.jar=63295:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\lucas\Desktop\RefactoringMiner-master\build\classes\java\main;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.jgit\org.eclipse.jgit\5.13.0.202109080827-r\32badd5adebd660424509344259ad3e409699ba2\org.eclipse.jgit-5.13.0.202109080827-r.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\junit\junit\4.13.2\8ac9e16d933b6fb43bc7f576336b8f4d7eb5ba12\junit-4.13.2.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.jdt\org.eclipse.jdt.core\3.30.0\2d6102201beb98b3c9a8ca36dbf82f9f8b71bc4c\org.eclipse.jdt.core-3.30.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-text\1.9\ba6ac8c2807490944a0a27f6f8e68fb5ed2e80e2\commons-text-1.9.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.kohsuke\github-api\1.135\341481e745101989254920c503da6d7d09a7bb05\github-api-1.135.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\io.github.java-diff-utils\java-diff-utils\4.11\e674e7408acefe082e7421d37f5d866e49dc468f\java-diff-utils-4.11.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\com.googlecode.javaewah\JavaEWAH\1.1.12\9feecc2b24d6bc9ff865af8d082f192238a293eb\JavaEWAH-1.1.12.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.36\6c62681a2f655b49963a5983b8b0950a6120ae14\slf4j-api-1.7.36.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-reload4j\1.7.36\db708f7d959dee1857ac524636e85ecf2e1781c1\slf4j-reload4j-1.7.36.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.resources\3.17.0\51efdd38434a3217351d6fedc085f6526c4bb76f\org.eclipse.core.resources-3.17.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.text\3.12.100\d26cfcba07d358aca7d6341104bb7584b1d6f03f\org.eclipse.text-3.12.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.runtime\3.25.0\e630a5704768b9b75c76606429f9321f5be79ed2\org.eclipse.core.runtime-3.25.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.filesystem\1.9.400\17ee4e04d08117777ce9575f3d54ec21d32fbcbe\org.eclipse.core.filesystem-1.9.400.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.11\68e9a6adf7cf8eb7e9d31bbc554c7c75eeaac568\commons-lang3-3.11.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.13.0\889672a1721d6d85b2834fcd29d3fda92c8c8891\jackson-databind-2.13.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.8.0\92999e26e6534606b5678014e66948286298a35c\commons-io-2.8.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\ch.qos.reload4j\reload4j\1.2.19\4eae9978468c5e885a6fb44df7e2bbc07a20e6ce\reload4j-1.2.19.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.expressions\3.8.100\454dcfbb7d770c486c07ec7348bf711eefed23bd\org.eclipse.core.expressions-3.8.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.equinox.preferences\3.10.1\151d943ca7473838bfa86671c66703de008bd5d8\org.eclipse.equinox.preferences-3.10.1.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.commands\3.10.200\bc5c1d5b16f5bdd49534ca364794a5946714c541\org.eclipse.core.commands-3.10.200.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.equinox.common\3.16.100\dc64019563130aca1186a5fe21c7e356fc7a863a\org.eclipse.equinox.common-3.16.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.jobs\3.13.0\bedc837540247be40813660e668c584ca610f7db\org.eclipse.core.jobs-3.13.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.core.contenttype\3.8.100\ae9b39e290e4e6d557d0ad8cfbb278e0bfabbe16\org.eclipse.core.contenttype-3.8.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.equinox.app\1.6.100\9553009ca914f20ef2da4909922d58c6b14dc7a6\org.eclipse.equinox.app-1.6.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.equinox.registry\3.11.100\713133f26871cc548cc28d013b35af051a0bb10c\org.eclipse.equinox.registry-3.11.100.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.eclipse.platform\org.eclipse.osgi\3.18.0\6f5d53b49a1f60559b39df01a16ac05e8cd13d75\org.eclipse.osgi-3.18.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.13.0\15be89db6609bd6fda3dc309bacf0318a312c03f\jackson-annotations-2.13.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.13.0\e957ec5442966e69cef543927bdc80e5426968bb\jackson-core-2.13.0.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.osgi\org.osgi.service.prefs\1.1.2\44351fdfb119ee920394c1a27c938288c93c03c8\org.osgi.service.prefs-1.1.2.jar;C:\Users\lucas\.gradle\caches\modules-2\files-2.1\org.osgi\osgi.annotation\8.0.1\593d823753aa6e128129da357d7891758e66aa1d\osgi.annotation-8.0.1.jar org.refactoringminer.RefactoringMiner -c tmp1/refactoring-toy-example 36287f7c3b09eff78395267a3ac0d7da067863fd -json output.json
---- IntelliJ IDEA coverage runner ---- 
sampling ...
include patterns:
org\.refactoringminer\..*
exclude patterns:
log4j:WARN No appenders could be found for logger (org.eclipse.jgit.internal.storage.file.FileSnapshot).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Error processing commit 36287f7c3b09eff78395267a3ac0d7da067863fd
java.lang.NullPointerException
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.extractRepositoryName(GitHistoryRefactoringMinerImpl.java:886)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.getGitHubRepository(GitHistoryRefactoringMinerImpl.java:877)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.populateWithGitHubAPI(GitHistoryRefactoringMinerImpl.java:449)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:321)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:575)
	at org.refactoringminer.RefactoringMiner.detectAtCommit(RefactoringMiner.java:193)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:41)
Exception in thread "main" java.lang.NullPointerException
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.extractCommitURL(GitHistoryRefactoringMinerImpl.java:904)
	at org.refactoringminer.RefactoringMiner.commitJSON(RefactoringMiner.java:292)
	at org.refactoringminer.RefactoringMiner$4.handle(RefactoringMiner.java:196)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:357)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:575)
	at org.refactoringminer.RefactoringMiner.detectAtCommit(RefactoringMiner.java:193)
	at org.refactoringminer.RefactoringMiner.main(RefactoringMiner.java:41)
Class transformation time: 0.1740566s for 2369 classes or 7.34726044744618E-5s per class

Process finished with exit code 1 ```

And that's the run config, don't know why the border was red previously
![image](https://user-images.githubusercontent.com/88104745/187230554-d636e171-7036-47d8-9115-1239305a1c25.png)

**Comment by tsantalis** [comment]
@lucasrafael1901
The last exception you report is related to the GitHub API, and happened because you did not specify the GitHub repository URL.

Please study carefully the [command line options](https://github.com/tsantalis/RefactoringMiner#running-refactoringminer-from-the-command-line)

For example to run the same case using the GitHub API (i.e., fetching the data directly from GitHub), you need the following arguments:
`-gc https://github.com/danilofes/refactoring-toy-example.git 36287f7c3b09eff78395267a3ac0d7da067863fd 10`

For the `-gc` and `-gp` options you must provide a valid OAuth token in the `github-oauth.properties` file stored in the `bin` folder.
You can generate an OAuth token in GitHub `Settings` -> `Developer settings` -> `Personal access tokens`.

I consider this issue closed, since the project was built successfully. All errors reported are due to missing or wrong arguments.

Moreover, since the tool was built successfully, you can execute it from the [command line](https://github.com/tsantalis/RefactoringMiner#running-refactoringminer-from-the-command-line), and avoid the execution through IntelliJ IDE.
